-- ─────────────────────────────────────────────────────────────────
-- migration.sql  — Create "education" table
--
-- HOW TO RUN THIS:
--   1. Go to your Supabase Dashboard -> SQL Editor
--   2. Copy this entire script and click "Run"
-- ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS education (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  institution text NOT NULL,
  degree text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  description text,
  is_published boolean DEFAULT true
);

-- Row Level Security (RLS) Policies
ALTER TABLE education ENABLE ROW LEVEL SECURITY;

-- Allow public read access to education
CREATE POLICY "Allow public read access on education" 
ON education FOR SELECT 
USING (true);

-- Allow authenticated users (Admins) to insert, update, and delete
CREATE POLICY "Allow authenticated users to insert education" 
ON education FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to update education" 
ON education FOR UPDATE 
USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to delete education" 
ON education FOR DELETE 
USING (auth.role() = 'authenticated');
