-- ─────────────────────────────────────────────────────────────────
-- FINAL DATABASE SCHEMA
-- This file represents the complete Supabase database structure
-- ─────────────────────────────────────────────────────────────────

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. PROFILES TABLE (Links to Auth)
-- ==========================================
create table profiles (
  id uuid references auth.users not null primary key,
  role text default 'user',
  constraint role_check check (role in ('user', 'admin'))
);

alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- ==========================================
-- 2. SITE SETTINGS TABLE
-- ==========================================
create table site_settings (
  section text primary key,
  content jsonb default '{}'::jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table site_settings enable row level security;
create policy "Allow public read access on site_settings" on site_settings for select using (true);
create policy "Allow authenticated users to insert site_settings" on site_settings for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated users to update site_settings" on site_settings for update using (auth.role() = 'authenticated');

-- ==========================================
-- 3. PROJECTS TABLE
-- ==========================================
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  description text,
  content text,
  tech_stack text[],
  is_published boolean default true,
  start_date date,
  end_date date,
  repositories jsonb default '[]'::jsonb,
  media jsonb default '[]'::jsonb,
  repo_url text,    -- legacy
  demo_url text,    -- legacy
  image_url text,   -- legacy
  video_url text,   -- legacy
  created_at timestamp with time zone default now()
);

alter table projects enable row level security;
create policy "Projects are viewable by everyone." on projects for select using (true);
create policy "Admins can insert projects." on projects for insert with check (auth.role() = 'authenticated');
create policy "Admins can update projects." on projects for update using (auth.role() = 'authenticated');
create policy "Admins can delete projects." on projects for delete using (auth.role() = 'authenticated');

-- ==========================================
-- 4. POSTS TABLE (Blog)
-- ==========================================
create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content jsonb,
  is_published boolean default false,
  image_url text,
  created_at timestamp with time zone default now(),
  published_at timestamp with time zone default timezone('utc'::text, now())
);

alter table posts enable row level security;
create policy "Published posts are viewable by everyone." on posts for select using (true);
create policy "Admins can insert posts." on posts for insert with check (auth.role() = 'authenticated');
create policy "Admins can update posts." on posts for update using (auth.role() = 'authenticated');
create policy "Admins can delete posts." on posts for delete using (auth.role() = 'authenticated');

-- ==========================================
-- 5. EXPERIENCES TABLE
-- ==========================================
create table experiences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company text not null,
  role text not null,
  start_date date not null,
  end_date date,
  description text,
  logo_url text,
  is_published boolean default true
);

alter table experiences enable row level security;
create policy "Allow public read access on experiences" on experiences for select using (true);
create policy "Allow authenticated users to insert experiences" on experiences for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated users to update experiences" on experiences for update using (auth.role() = 'authenticated');
create policy "Allow authenticated users to delete experiences" on experiences for delete using (auth.role() = 'authenticated');

-- ==========================================
-- 6. EDUCATION TABLE
-- ==========================================
create table education (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  institution text not null,
  degree text not null,
  start_date date not null,
  end_date date,
  description text,
  is_published boolean default true
);

alter table education enable row level security;
create policy "Allow public read access on education" on education for select using (true);
create policy "Allow authenticated users to insert education" on education for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated users to update education" on education for update using (auth.role() = 'authenticated');
create policy "Allow authenticated users to delete education" on education for delete using (auth.role() = 'authenticated');

-- ==========================================
-- 7. CONTACT MESSAGES TABLE
-- ==========================================
create table contact_messages (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false
);

alter table contact_messages enable row level security;
create policy "Allow public insert to contact_messages" on contact_messages for insert with check (true);
create policy "Allow authenticated users to read contact_messages" on contact_messages for select using (auth.role() = 'authenticated');
create policy "Allow authenticated users to update contact_messages" on contact_messages for update using (auth.role() = 'authenticated');
create policy "Allow authenticated users to delete contact_messages" on contact_messages for delete using (auth.role() = 'authenticated');