-- Add site_settings table for customizable content
create table site_settings (
  id bigint generated by default as identity primary key,
  section text unique not null, -- 'hero', 'about', 'contact', 'resume', 'navbar', 'footer'
  content jsonb not null, -- Flexible JSON structure for each section
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table site_settings enable row level security;

-- Public read access
create policy "Site settings are viewable by everyone." on site_settings
  for select using (true);

-- Admin write access
create policy "Admins can update site settings." on site_settings
  for update using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Admins can insert site settings." on site_settings
  for insert with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Insert default settings
insert into site_settings (section, content) values
('hero', '{
  "title": "Building Digital Experiences.",
  "subtitle": "Hi, I am Bhanura Waduge. A Professional Full Stack Developer specializing in building exceptional digital products.",
  "headshotUrl": "",
  "primaryButtonText": "View Projects",
  "primaryButtonLink": "/projects",
  "secondaryButtonText": "My Resume",
  "secondaryButtonLink": "/resume"
}'),
('navbar', '{
  "logo": "BW",
  "name": "Bhanura Waduge",
  "links": [
    {"label": "Projects", "href": "/projects", "icon": "briefcase"},
    {"label": "Resume", "href": "/resume", "icon": "file"},
    {"label": "Blog", "href": "/blog", "icon": "pen"},
    {"label": "Contact", "href": "#contact", "icon": "mail"}
  ]
}'),
('footer', '{
  "copyright": "Bhanura Waduge. All rights reserved.",
  "socialLinks": [
    {"label": "GitHub", "href": "https://github.com"},
    {"label": "LinkedIn", "href": "https://linkedin.com"}
  ]
}'),
('contact', '{
  "title": "Get In Touch",
  "email": "contact@bhanura.dev",
  "successMessage": "Thank you for your message! I will get back to you soon."
}'),
('resume_experience', '{
  "items": [
    {
      "title": "Senior Developer",
      "company": "Tech Corp Inc.",
      "period": "2023 - Present",
      "description": [
        "Led the migration of legacy app to Next.js 14.",
        "Improved site performance by 40% using SSR and ISR.",
        "Mentored junior developers and conducted code reviews."
      ]
    },
    {
      "title": "Web Developer",
      "company": "Creative Solutions Agency",
      "period": "2020 - 2023",
      "description": [
        "Developed responsive websites for diverse clients.",
        "Integrated Supabase for backend needs.",
        "Collaborated with designers to implement pixel-perfect UIs."
      ]
    }
  ]
}'),
('resume_education', '{
  "items": [
    {
      "degree": "BSc in Computer Science",
      "school": "University of Technology",
      "period": "2016 - 2020"
    }
  ]
}'),
('resume_skills', '{
  "items": ["JavaScript", "TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "Tailwind CSS", "Git", "CI/CD"]
}'),
('resume_header', '{
  "name": "Bhanura Waduge",
  "title": "Full Stack Developer",
  "location": "San Francisco, CA",
  "email": "contact@bhanura.dev",
  "linkedin": "linkedin.com/in/bhanura",
  "headshotUrl": "",
  "summary": "Experienced Full Stack Developer with a passion for building scalable web applications. Proficient in JavaScript, TypeScript, React, Next.js, and Node.js. Dedicated to clean code, performance optimization, and user-centric design."
}');
